"""initial

Revision ID: d91babd71140
Revises: None
Create Date: 2026-09-13 04:16:19.660770
"""

from alembic import op
import sqlalchemy as sa


revision = 'd91babd71140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_api_tokens_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('digest', name=op.f('uq_api_tokens_digest'))
    )
    op.create_table('notes',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('body', sa.String(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_notes_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'user_id', name=op.f('pk_notes'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tags_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('owner_id', 'id', name=op.f('uq_tags_owner_id_id')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_tags_owner_id_name'))
    )
    op.create_table('note_tags',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id', 'tag_id'], ['tags.owner_id', 'tags.id'], name=op.f('fk_note_tags_owner_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id', 'user_id'], ['notes.owner_id', 'notes.user_id'], name=op.f('fk_note_tags_owner_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'user_id', 'tag_id', name=op.f('pk_note_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    op.drop_table('tags')
    op.drop_table('notes')
    op.drop_table('api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###